// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type McpToken struct {
	ID         pgtype.UUID      `json:"id"`
	Token      pgtype.UUID      `json:"token"`
	UserID     string           `json:"user_id"`
	Name       string           `json:"name"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
	IsActive   bool             `json:"is_active"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	OwnerID   string             `json:"owner_id"`
}

type Task struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	OwnerID   string             `json:"owner_id"`
}
