// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChecklistItem = `-- name: AddChecklistItem :one
INSERT INTO task_checklist_items (task_id, content, completed, sort_order)
SELECT $1, $2, FALSE,
       COALESCE((SELECT MAX(sort_order) + 1 FROM task_checklist_items WHERE task_id = $1), 0)
FROM tasks
WHERE id = $1 AND owner_id = $3
RETURNING id, task_id, content, completed, sort_order, created_at, updated_at
`

type AddChecklistItemParams struct {
	TaskID  pgtype.UUID `json:"task_id"`
	Content string      `json:"content"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) AddChecklistItem(ctx context.Context, arg AddChecklistItemParams) (TaskChecklistItem, error) {
	row := q.db.QueryRow(ctx, addChecklistItem, arg.TaskID, arg.Content, arg.OwnerID)
	var i TaskChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Completed,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveTask = `-- name: ArchiveTask :one
UPDATE tasks
SET archived_at = NOW(), updated_at = NOW()
WHERE id = $1 AND owner_id = $2
RETURNING id, title, notes, owner_id, archived_at, created_at, updated_at, start_date
`

type ArchiveTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

type ArchiveTaskRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Notes      string             `json:"notes"`
	OwnerID    string             `json:"owner_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	StartDate  pgtype.Date        `json:"start_date"`
}

func (q *Queries) ArchiveTask(ctx context.Context, arg ArchiveTaskParams) (ArchiveTaskRow, error) {
	row := q.db.QueryRow(ctx, archiveTask, arg.ID, arg.OwnerID)
	var i ArchiveTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.OwnerID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, notes, owner_id, start_date)
VALUES ($1, $2, $3, $4)
RETURNING id, title, notes, owner_id, archived_at, created_at, updated_at, start_date
`

type CreateTaskParams struct {
	Title     string      `json:"title"`
	Notes     string      `json:"notes"`
	OwnerID   string      `json:"owner_id"`
	StartDate pgtype.Date `json:"start_date"`
}

type CreateTaskRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Notes      string             `json:"notes"`
	OwnerID    string             `json:"owner_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	StartDate  pgtype.Date        `json:"start_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.Title,
		arg.Notes,
		arg.OwnerID,
		arg.StartDate,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.OwnerID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
	)
	return i, err
}

const createTaskTag = `-- name: CreateTaskTag :exec
INSERT INTO task_tags (task_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateTaskTagParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

func (q *Queries) CreateTaskTag(ctx context.Context, arg CreateTaskTagParams) error {
	_, err := q.db.Exec(ctx, createTaskTag, arg.TaskID, arg.TagID)
	return err
}

const deleteChecklistItem = `-- name: DeleteChecklistItem :execrows
DELETE FROM task_checklist_items ci
USING tasks t
WHERE ci.id = $1
  AND ci.task_id = t.id
  AND t.owner_id = $2
`

type DeleteChecklistItemParams struct {
	ItemID  pgtype.UUID `json:"item_id"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) DeleteChecklistItem(ctx context.Context, arg DeleteChecklistItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChecklistItem, arg.ItemID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1 AND owner_id = $2
`

type DeleteTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.OwnerID)
	return err
}

const deleteTaskTags = `-- name: DeleteTaskTags :exec
DELETE FROM task_tags
WHERE task_id = $1
`

func (q *Queries) DeleteTaskTags(ctx context.Context, taskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskTags, taskID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, notes, owner_id, archived_at, created_at, updated_at, start_date
FROM tasks
WHERE id = $1 AND owner_id = $2
`

type GetTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

type GetTaskRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Notes      string             `json:"notes"`
	OwnerID    string             `json:"owner_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	StartDate  pgtype.Date        `json:"start_date"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.OwnerID)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.OwnerID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
	)
	return i, err
}

const getTaskTagIDs = `-- name: GetTaskTagIDs :many
SELECT tag_id
FROM task_tags
WHERE task_id = $1
`

func (q *Queries) GetTaskTagIDs(ctx context.Context, taskID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getTaskTagIDs, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var tag_id pgtype.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklistItems = `-- name: ListChecklistItems :many
SELECT ci.id, ci.task_id, ci.content, ci.completed, ci.sort_order, ci.created_at, ci.updated_at
FROM task_checklist_items ci
JOIN tasks t ON ci.task_id = t.id
WHERE ci.task_id = $1 AND t.owner_id = $2
ORDER BY ci.sort_order ASC, ci.created_at ASC
`

type ListChecklistItemsParams struct {
	TaskID  pgtype.UUID `json:"task_id"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) ListChecklistItems(ctx context.Context, arg ListChecklistItemsParams) ([]TaskChecklistItem, error) {
	rows, err := q.db.Query(ctx, listChecklistItems, arg.TaskID, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskChecklistItem{}
	for rows.Next() {
		var i TaskChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Content,
			&i.Completed,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT DISTINCT t.id, t.title, t.notes, t.owner_id, t.archived_at, t.created_at, t.updated_at, t.start_date
FROM tasks t
LEFT JOIN task_tags tt ON t.id = tt.task_id
WHERE t.owner_id = $1
  AND ($4::uuid[] IS NULL
       OR tt.tag_id = ANY($4::uuid[]))
  AND (
    ($5::boolean = TRUE AND t.archived_at IS NOT NULL) OR
    ($5::boolean = FALSE AND (
      $6::boolean = TRUE OR
      ($6::boolean = FALSE AND t.archived_at IS NULL)
    )) OR
    ($5::boolean IS NULL AND $6::boolean IS NULL AND t.archived_at IS NULL)
  )
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksParams struct {
	OwnerID         string        `json:"owner_id"`
	Limit           int32         `json:"limit"`
	Offset          int32         `json:"offset"`
	FilterTagIds    []pgtype.UUID `json:"filter_tag_ids"`
	ArchivedOnly    pgtype.Bool   `json:"archived_only"`
	IncludeArchived pgtype.Bool   `json:"include_archived"`
}

type ListTasksRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Notes      string             `json:"notes"`
	OwnerID    string             `json:"owner_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	StartDate  pgtype.Date        `json:"start_date"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.OwnerID,
		arg.Limit,
		arg.Offset,
		arg.FilterTagIds,
		arg.ArchivedOnly,
		arg.IncludeArchived,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.OwnerID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StartDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reorderChecklistItems = `-- name: ReorderChecklistItems :exec
UPDATE task_checklist_items ci
SET sort_order = (ordered.ord - 1)::int,
    updated_at = NOW()
FROM unnest($2::uuid[]) WITH ORDINALITY AS ordered(id, ord)
JOIN tasks t ON t.id = $1 AND t.owner_id = $3
WHERE ci.task_id = $1
  AND ci.id = ordered.id
`

type ReorderChecklistItemsParams struct {
	TaskID  pgtype.UUID   `json:"task_id"`
	ItemIds []pgtype.UUID `json:"item_ids"`
	OwnerID string        `json:"owner_id"`
}

func (q *Queries) ReorderChecklistItems(ctx context.Context, arg ReorderChecklistItemsParams) error {
	_, err := q.db.Exec(ctx, reorderChecklistItems, arg.TaskID, arg.ItemIds, arg.OwnerID)
	return err
}

const setChecklistItemCompleted = `-- name: SetChecklistItemCompleted :one
UPDATE task_checklist_items ci
SET completed = $1, updated_at = NOW()
FROM tasks t
WHERE ci.id = $2
  AND ci.task_id = t.id
  AND t.owner_id = $3
RETURNING ci.id, ci.task_id, ci.content, ci.completed, ci.sort_order, ci.created_at, ci.updated_at
`

type SetChecklistItemCompletedParams struct {
	Completed bool        `json:"completed"`
	ItemID    pgtype.UUID `json:"item_id"`
	OwnerID   string      `json:"owner_id"`
}

func (q *Queries) SetChecklistItemCompleted(ctx context.Context, arg SetChecklistItemCompletedParams) (TaskChecklistItem, error) {
	row := q.db.QueryRow(ctx, setChecklistItemCompleted, arg.Completed, arg.ItemID, arg.OwnerID)
	var i TaskChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Completed,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unarchiveTask = `-- name: UnarchiveTask :one
UPDATE tasks
SET archived_at = NULL, updated_at = NOW()
WHERE id = $1 AND owner_id = $2
RETURNING id, title, notes, owner_id, archived_at, created_at, updated_at, start_date
`

type UnarchiveTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

type UnarchiveTaskRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Notes      string             `json:"notes"`
	OwnerID    string             `json:"owner_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	StartDate  pgtype.Date        `json:"start_date"`
}

func (q *Queries) UnarchiveTask(ctx context.Context, arg UnarchiveTaskParams) (UnarchiveTaskRow, error) {
	row := q.db.QueryRow(ctx, unarchiveTask, arg.ID, arg.OwnerID)
	var i UnarchiveTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.OwnerID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
	)
	return i, err
}

const updateChecklistItemContent = `-- name: UpdateChecklistItemContent :one
UPDATE task_checklist_items ci
SET content = $1, updated_at = NOW()
FROM tasks t
WHERE ci.id = $2
  AND ci.task_id = t.id
  AND t.owner_id = $3
RETURNING ci.id, ci.task_id, ci.content, ci.completed, ci.sort_order, ci.created_at, ci.updated_at
`

type UpdateChecklistItemContentParams struct {
	Content string      `json:"content"`
	ItemID  pgtype.UUID `json:"item_id"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) UpdateChecklistItemContent(ctx context.Context, arg UpdateChecklistItemContentParams) (TaskChecklistItem, error) {
	row := q.db.QueryRow(ctx, updateChecklistItemContent, arg.Content, arg.ItemID, arg.OwnerID)
	var i TaskChecklistItem
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Content,
		&i.Completed,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $2, notes = $3, updated_at = NOW(), start_date = $5
WHERE id = $1 AND owner_id = $4
RETURNING id, title, notes, owner_id, archived_at, created_at, updated_at, start_date
`

type UpdateTaskParams struct {
	ID        pgtype.UUID `json:"id"`
	Title     string      `json:"title"`
	Notes     string      `json:"notes"`
	OwnerID   string      `json:"owner_id"`
	StartDate pgtype.Date `json:"start_date"`
}

type UpdateTaskRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Notes      string             `json:"notes"`
	OwnerID    string             `json:"owner_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	StartDate  pgtype.Date        `json:"start_date"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Notes,
		arg.OwnerID,
		arg.StartDate,
	)
	var i UpdateTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.OwnerID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartDate,
	)
	return i, err
}
