// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: task.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, notes, owner_id)
VALUES ($1, $2, $3)
RETURNING id, title, notes, owner_id, created_at, updated_at
`

type CreateTaskParams struct {
	Title   string `json:"title"`
	Notes   string `json:"notes"`
	OwnerID string `json:"owner_id"`
}

type CreateTaskRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Notes     string             `json:"notes"`
	OwnerID   string             `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Title, arg.Notes, arg.OwnerID)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1 AND owner_id = $2
`

type DeleteTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.OwnerID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, notes, owner_id, created_at, updated_at
FROM tasks
WHERE id = $1 AND owner_id = $2
`

type GetTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

type GetTaskRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Notes     string             `json:"notes"`
	OwnerID   string             `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.OwnerID)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, notes, owner_id, created_at, updated_at
FROM tasks
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksParams struct {
	OwnerID string `json:"owner_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListTasksRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Notes     string             `json:"notes"`
	OwnerID   string             `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $2, notes = $3, updated_at = NOW()
WHERE id = $1 AND owner_id = $4
RETURNING id, title, notes, owner_id, created_at, updated_at
`

type UpdateTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	Title   string      `json:"title"`
	Notes   string      `json:"notes"`
	OwnerID string      `json:"owner_id"`
}

type UpdateTaskRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Notes     string             `json:"notes"`
	OwnerID   string             `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Notes,
		arg.OwnerID,
	)
	var i UpdateTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
