// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: task.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveTask = `-- name: ArchiveTask :one
UPDATE tasks
SET archived_at = NOW(), updated_at = NOW()
WHERE id = $1 AND owner_id = $2
RETURNING id, title, notes, owner_id, archived_at, created_at, updated_at
`

type ArchiveTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

type ArchiveTaskRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Notes      string             `json:"notes"`
	OwnerID    string             `json:"owner_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ArchiveTask(ctx context.Context, arg ArchiveTaskParams) (ArchiveTaskRow, error) {
	row := q.db.QueryRow(ctx, archiveTask, arg.ID, arg.OwnerID)
	var i ArchiveTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.OwnerID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (title, notes, owner_id)
VALUES ($1, $2, $3)
RETURNING id, title, notes, owner_id, archived_at, created_at, updated_at
`

type CreateTaskParams struct {
	Title   string `json:"title"`
	Notes   string `json:"notes"`
	OwnerID string `json:"owner_id"`
}

type CreateTaskRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Notes      string             `json:"notes"`
	OwnerID    string             `json:"owner_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Title, arg.Notes, arg.OwnerID)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.OwnerID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTaskTag = `-- name: CreateTaskTag :exec
INSERT INTO task_tags (task_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateTaskTagParams struct {
	TaskID pgtype.UUID `json:"task_id"`
	TagID  pgtype.UUID `json:"tag_id"`
}

func (q *Queries) CreateTaskTag(ctx context.Context, arg CreateTaskTagParams) error {
	_, err := q.db.Exec(ctx, createTaskTag, arg.TaskID, arg.TagID)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1 AND owner_id = $2
`

type DeleteTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.OwnerID)
	return err
}

const deleteTaskTags = `-- name: DeleteTaskTags :exec
DELETE FROM task_tags
WHERE task_id = $1
`

func (q *Queries) DeleteTaskTags(ctx context.Context, taskID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskTags, taskID)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, title, notes, owner_id, archived_at, created_at, updated_at
FROM tasks
WHERE id = $1 AND owner_id = $2
`

type GetTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

type GetTaskRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Notes      string             `json:"notes"`
	OwnerID    string             `json:"owner_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, arg.ID, arg.OwnerID)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.OwnerID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskTagIDs = `-- name: GetTaskTagIDs :many
SELECT tag_id
FROM task_tags
WHERE task_id = $1
`

func (q *Queries) GetTaskTagIDs(ctx context.Context, taskID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getTaskTagIDs, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var tag_id pgtype.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT DISTINCT t.id, t.title, t.notes, t.owner_id, t.archived_at, t.created_at, t.updated_at
FROM tasks t
LEFT JOIN task_tags tt ON t.id = tt.task_id
WHERE t.owner_id = $1
  AND ($4::uuid[] IS NULL
       OR tt.tag_id = ANY($4::uuid[]))
  AND (
    ($5::boolean = TRUE AND t.archived_at IS NOT NULL) OR
    ($5::boolean = FALSE AND (
      $6::boolean = TRUE OR
      ($6::boolean = FALSE AND t.archived_at IS NULL)
    )) OR
    ($5::boolean IS NULL AND $6::boolean IS NULL AND t.archived_at IS NULL)
  )
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type ListTasksParams struct {
	OwnerID         string        `json:"owner_id"`
	Limit           int32         `json:"limit"`
	Offset          int32         `json:"offset"`
	FilterTagIds    []pgtype.UUID `json:"filter_tag_ids"`
	ArchivedOnly    pgtype.Bool   `json:"archived_only"`
	IncludeArchived pgtype.Bool   `json:"include_archived"`
}

type ListTasksRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Notes      string             `json:"notes"`
	OwnerID    string             `json:"owner_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.OwnerID,
		arg.Limit,
		arg.Offset,
		arg.FilterTagIds,
		arg.ArchivedOnly,
		arg.IncludeArchived,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Notes,
			&i.OwnerID,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchiveTask = `-- name: UnarchiveTask :one
UPDATE tasks
SET archived_at = NULL, updated_at = NOW()
WHERE id = $1 AND owner_id = $2
RETURNING id, title, notes, owner_id, archived_at, created_at, updated_at
`

type UnarchiveTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

type UnarchiveTaskRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Notes      string             `json:"notes"`
	OwnerID    string             `json:"owner_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UnarchiveTask(ctx context.Context, arg UnarchiveTaskParams) (UnarchiveTaskRow, error) {
	row := q.db.QueryRow(ctx, unarchiveTask, arg.ID, arg.OwnerID)
	var i UnarchiveTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.OwnerID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title = $2, notes = $3, updated_at = NOW()
WHERE id = $1 AND owner_id = $4
RETURNING id, title, notes, owner_id, archived_at, created_at, updated_at
`

type UpdateTaskParams struct {
	ID      pgtype.UUID `json:"id"`
	Title   string      `json:"title"`
	Notes   string      `json:"notes"`
	OwnerID string      `json:"owner_id"`
}

type UpdateTaskRow struct {
	ID         pgtype.UUID        `json:"id"`
	Title      string             `json:"title"`
	Notes      string             `json:"notes"`
	OwnerID    string             `json:"owner_id"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Notes,
		arg.OwnerID,
	)
	var i UpdateTaskRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.OwnerID,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
