// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: mcp_token.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMCPToken = `-- name: CreateMCPToken :one
INSERT INTO mcp_tokens (token, user_id, name, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, token, user_id, name, created_at, expires_at, last_used_at, is_active
`

type CreateMCPTokenParams struct {
	Token     pgtype.UUID      `json:"token"`
	UserID    string           `json:"user_id"`
	Name      string           `json:"name"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateMCPToken(ctx context.Context, arg CreateMCPTokenParams) (McpToken, error) {
	row := q.db.QueryRow(ctx, createMCPToken,
		arg.Token,
		arg.UserID,
		arg.Name,
		arg.ExpiresAt,
	)
	var i McpToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsActive,
	)
	return i, err
}

const deleteMCPToken = `-- name: DeleteMCPToken :exec
DELETE FROM mcp_tokens
WHERE id = $1
`

func (q *Queries) DeleteMCPToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMCPToken, id)
	return err
}

const getMCPTokenByID = `-- name: GetMCPTokenByID :one
SELECT id, token, user_id, name, created_at, expires_at, last_used_at, is_active
FROM mcp_tokens
WHERE id = $1
`

func (q *Queries) GetMCPTokenByID(ctx context.Context, id pgtype.UUID) (McpToken, error) {
	row := q.db.QueryRow(ctx, getMCPTokenByID, id)
	var i McpToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsActive,
	)
	return i, err
}

const getMCPTokenByToken = `-- name: GetMCPTokenByToken :one
SELECT id, token, user_id, name, created_at, expires_at, last_used_at, is_active
FROM mcp_tokens
WHERE token = $1
`

func (q *Queries) GetMCPTokenByToken(ctx context.Context, token pgtype.UUID) (McpToken, error) {
	row := q.db.QueryRow(ctx, getMCPTokenByToken, token)
	var i McpToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.IsActive,
	)
	return i, err
}

const listMCPTokensByUserID = `-- name: ListMCPTokensByUserID :many
SELECT id, token, user_id, name, created_at, expires_at, last_used_at, is_active
FROM mcp_tokens
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListMCPTokensByUserID(ctx context.Context, userID string) ([]McpToken, error) {
	rows, err := q.db.Query(ctx, listMCPTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []McpToken{}
	for rows.Next() {
		var i McpToken
		if err := rows.Scan(
			&i.ID,
			&i.Token,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMCPToken = `-- name: RevokeMCPToken :exec
UPDATE mcp_tokens
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) RevokeMCPToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeMCPToken, id)
	return err
}

const updateMCPTokenLastUsedAt = `-- name: UpdateMCPTokenLastUsedAt :exec
UPDATE mcp_tokens
SET last_used_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateMCPTokenLastUsedAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateMCPTokenLastUsedAt, id)
	return err
}
