// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateMCPToken(ctx context.Context, arg CreateMCPTokenParams) (McpToken, error)
	DeleteMCPToken(ctx context.Context, id pgtype.UUID) error
	GetMCPTokenByID(ctx context.Context, id pgtype.UUID) (McpToken, error)
	GetMCPTokenByToken(ctx context.Context, token pgtype.UUID) (McpToken, error)
	ListMCPTokensByUserID(ctx context.Context, userID string) ([]McpToken, error)
	RevokeMCPToken(ctx context.Context, id pgtype.UUID) error
	UpdateMCPTokenLastUsedAt(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
