// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateTag(ctx context.Context, arg CreateTagParams) (CreateTagRow, error)
	DeleteOrphanTags(ctx context.Context, ownerID string) error
	DeleteTag(ctx context.Context, arg DeleteTagParams) error
	GetTag(ctx context.Context, arg GetTagParams) (GetTagRow, error)
	GetTagByName(ctx context.Context, arg GetTagByNameParams) (GetTagByNameRow, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (UpdateTagRow, error)
}

var _ Querier = (*Queries)(nil)
