// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTag(ctx context.Context, name string) (Tag, error)
	DeleteTag(ctx context.Context, id pgtype.UUID) error
	GetTag(ctx context.Context, id pgtype.UUID) (Tag, error)
	ListTags(ctx context.Context, arg ListTagsParams) ([]Tag, error)
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
}

var _ Querier = (*Queries)(nil)
