// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, created_at, updated_at
`

type CreateTagParams struct {
	Name    string `json:"name"`
	OwnerID string `json:"owner_id"`
}

type CreateTagRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OwnerID   string             `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (CreateTagRow, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.OwnerID)
	var i CreateTagRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrphanTags = `-- name: DeleteOrphanTags :exec
DELETE FROM tags
WHERE owner_id = $1
  AND id NOT IN (
    SELECT DISTINCT tag_id
    FROM task_tags
  )
`

func (q *Queries) DeleteOrphanTags(ctx context.Context, ownerID string) error {
	_, err := q.db.Exec(ctx, deleteOrphanTags, ownerID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags
WHERE id = $1 AND owner_id = $2
`

type DeleteTagParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.Exec(ctx, deleteTag, arg.ID, arg.OwnerID)
	return err
}

const getTag = `-- name: GetTag :one
SELECT id, name, owner_id, created_at, updated_at
FROM tags
WHERE id = $1 AND owner_id = $2
`

type GetTagParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

type GetTagRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OwnerID   string             `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTag(ctx context.Context, arg GetTagParams) (GetTagRow, error) {
	row := q.db.QueryRow(ctx, getTag, arg.ID, arg.OwnerID)
	var i GetTagRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByName = `-- name: GetTagByName :one
SELECT id, name, owner_id, created_at, updated_at
FROM tags
WHERE name = $1 AND owner_id = $2
`

type GetTagByNameParams struct {
	Name    string `json:"name"`
	OwnerID string `json:"owner_id"`
}

type GetTagByNameRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OwnerID   string             `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTagByName(ctx context.Context, arg GetTagByNameParams) (GetTagByNameRow, error) {
	row := q.db.QueryRow(ctx, getTagByName, arg.Name, arg.OwnerID)
	var i GetTagByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, name, owner_id, created_at, updated_at
FROM tags
WHERE owner_id = $1
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListTagsParams struct {
	OwnerID string `json:"owner_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListTagsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OwnerID   string             `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, arg.OwnerID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags
SET name = $2, updated_at = NOW()
WHERE id = $1 AND owner_id = $3
RETURNING id, name, owner_id, created_at, updated_at
`

type UpdateTagParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	OwnerID string      `json:"owner_id"`
}

type UpdateTagRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	OwnerID   string             `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (UpdateTagRow, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.ID, arg.Name, arg.OwnerID)
	var i UpdateTagRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
