// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type McpToken struct {
	ID         pgtype.UUID      `json:"id"`
	Token      pgtype.UUID      `json:"token"`
	UserID     string           `json:"user_id"`
	Name       string           `json:"name"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
	IsActive   bool             `json:"is_active"`
}

type Tag struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	OwnerID   string             `json:"owner_id"`
}

type Task struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Notes         string             `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	OwnerID       string             `json:"owner_id"`
	ArchivedAt    pgtype.Timestamptz `json:"archived_at"`
	StartDateKind string             `json:"start_date_kind"`
	StartDate     pgtype.Date        `json:"start_date"`
}

type TaskTag struct {
	TaskID    pgtype.UUID        `json:"task_id"`
	TagID     pgtype.UUID        `json:"tag_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        int32            `json:"id"`
	UserID    string           `json:"user_id"`
	Username  pgtype.Text      `json:"username"`
	AvatarUrl pgtype.Text      `json:"avatar_url"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	Email     pgtype.Text      `json:"email"`
}
