// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"
)

type Querier interface {
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	GetUserByUserID(ctx context.Context, userID string) (GetUserByUserIDRow, error)
	UpdateUserTavilyMCPToken(ctx context.Context, arg UpdateUserTavilyMCPTokenParams) (UpdateUserTavilyMCPTokenRow, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (UpsertUserRow, error)
}

var _ Querier = (*Queries)(nil)
