// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_id, username, avatar_url, email, tavily_mcp_token, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID             int32            `json:"id"`
	UserID         string           `json:"user_id"`
	Username       pgtype.Text      `json:"username"`
	AvatarUrl      pgtype.Text      `json:"avatar_url"`
	Email          pgtype.Text      `json:"email"`
	TavilyMcpToken pgtype.Text      `json:"tavily_mcp_token"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.AvatarUrl,
		&i.Email,
		&i.TavilyMcpToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT id, user_id, username, avatar_url, email, tavily_mcp_token, created_at, updated_at
FROM users
WHERE user_id = $1
`

type GetUserByUserIDRow struct {
	ID             int32            `json:"id"`
	UserID         string           `json:"user_id"`
	Username       pgtype.Text      `json:"username"`
	AvatarUrl      pgtype.Text      `json:"avatar_url"`
	Email          pgtype.Text      `json:"email"`
	TavilyMcpToken pgtype.Text      `json:"tavily_mcp_token"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetUserByUserID(ctx context.Context, userID string) (GetUserByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByUserID, userID)
	var i GetUserByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.AvatarUrl,
		&i.Email,
		&i.TavilyMcpToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserTavilyMCPToken = `-- name: UpdateUserTavilyMCPToken :one
UPDATE users
SET tavily_mcp_token = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = $1
RETURNING id, user_id, username, avatar_url, email, tavily_mcp_token, created_at, updated_at
`

type UpdateUserTavilyMCPTokenParams struct {
	UserID         string      `json:"user_id"`
	TavilyMcpToken pgtype.Text `json:"tavily_mcp_token"`
}

type UpdateUserTavilyMCPTokenRow struct {
	ID             int32            `json:"id"`
	UserID         string           `json:"user_id"`
	Username       pgtype.Text      `json:"username"`
	AvatarUrl      pgtype.Text      `json:"avatar_url"`
	Email          pgtype.Text      `json:"email"`
	TavilyMcpToken pgtype.Text      `json:"tavily_mcp_token"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateUserTavilyMCPToken(ctx context.Context, arg UpdateUserTavilyMCPTokenParams) (UpdateUserTavilyMCPTokenRow, error) {
	row := q.db.QueryRow(ctx, updateUserTavilyMCPToken, arg.UserID, arg.TavilyMcpToken)
	var i UpdateUserTavilyMCPTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.AvatarUrl,
		&i.Email,
		&i.TavilyMcpToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (user_id, username, avatar_url, email, tavily_mcp_token, updated_at)
VALUES ($1, $2, $3, $4, $5, CURRENT_TIMESTAMP)
ON CONFLICT (user_id) DO UPDATE
SET 
    username = COALESCE(users.username, EXCLUDED.username),
    avatar_url = COALESCE(users.avatar_url, EXCLUDED.avatar_url),
    email = COALESCE(users.email, EXCLUDED.email),
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, username, avatar_url, email, tavily_mcp_token, created_at, updated_at
`

type UpsertUserParams struct {
	UserID         string      `json:"user_id"`
	Username       pgtype.Text `json:"username"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
	Email          pgtype.Text `json:"email"`
	TavilyMcpToken pgtype.Text `json:"tavily_mcp_token"`
}

type UpsertUserRow struct {
	ID             int32            `json:"id"`
	UserID         string           `json:"user_id"`
	Username       pgtype.Text      `json:"username"`
	AvatarUrl      pgtype.Text      `json:"avatar_url"`
	Email          pgtype.Text      `json:"email"`
	TavilyMcpToken pgtype.Text      `json:"tavily_mcp_token"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (UpsertUserRow, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.UserID,
		arg.Username,
		arg.AvatarUrl,
		arg.Email,
		arg.TavilyMcpToken,
	)
	var i UpsertUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.AvatarUrl,
		&i.Email,
		&i.TavilyMcpToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
