// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_id, username, avatar_url, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUserID = `-- name: GetUserByUserID :one
SELECT id, user_id, username, avatar_url, created_at, updated_at
FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByUserID(ctx context.Context, userID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUserID, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (user_id, username, avatar_url, updated_at)
VALUES ($1, $2, $3, CURRENT_TIMESTAMP)
ON CONFLICT (user_id) DO UPDATE
SET 
    username = EXCLUDED.username,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = CURRENT_TIMESTAMP
WHERE users.username IS NULL OR users.avatar_url IS NULL
RETURNING id, user_id, username, avatar_url, created_at, updated_at
`

type UpsertUserParams struct {
	UserID    string      `json:"user_id"`
	Username  pgtype.Text `json:"username"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.UserID, arg.Username, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Username,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
